### ISSUE TITLE
Navigation verlinkt zu (noch) nicht veröffentlichten Nachrichten

### ISSUE THREAD

**Issue by johannes-bittner** [inspiredminds/contao-sibling-navigation#10]
Offenbar prüft die Navigation nicht, ob Nachrichten auch schon sichtbar/publiziert sind - ich habe hier den Fall, dass die Publikation einer Nachricht auf den kommenden Tag terminiert ist (= in einer gewöhnlichen Liste bis dahin nicht angezeigt), der Link der sibling-navigation aber bereits im Frontend ausgegeben wird.  
![grafik](https://user-images.githubusercontent.com/1597697/93504136-5f80da00-f919-11ea-9afb-0881c4bcdf0b.png)
Lässt sich das irgendwie abfangen?

**Comment by fritzmg** [comment]
Ja, das wurde tatsächlich für Nachrichten bisher nicht berücksichtigt. Bitte die aktuelle `dev-master` Version testen.

**Comment by johannes-bittner** [comment]
Gerade getestet - Contao-Fehlermeldung im Preview, im Debug-Modus erhalte ich die Weiterleitungs-Fehlermeldung:  
`Diese Seite funktioniert nicht
... hat Sie zu oft weitergeleitet.
Löschen Sie Ihre Cookies.
ERR_TOO_MANY_REDIRECTS`

... allerdings nur auf der Reader-Seite - ?

**Comment by fritzmg** [comment]
Hm 🤔 ich denke nicht, dass das etwas mit den Änderungen zu tun hat. Funktioniert es wieder, wenn auf Version `1.2.0` zurück aktualisiert wird?

**Comment by johannes-bittner** [comment]
... ja, mit 1.2 gehts, mit dev-master definitiv nicht. Aber der Weiterleitungsfehler ist immer noch da ... 🙈 ... sobald das Leser-Modul auf der Seite angezeigt wird. Das macht es dann natürlich etwas schwierig, eine Fehlermeldung zu erhalten ...

**Comment by johannes-bittner** [comment]
Hm ... wenn ich [https://github.com/fritzmg/contao-simple-news-urls](url) deinstalliere, klappts auch mit der Fehlermeldung 😉
(aber schade eigentlich ...)


`Unknown method isPreviewMode`

> Exception:
> Unknown method isPreviewMode
> 
>   at vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model.php:1003
>   at Contao\Model::__callStatic('isPreviewMode', array())
>      (vendor/inspiredminds/contao-sibling-navigation/src/Module/SiblingNavigationNews.php:109)
>   at InspiredMinds\ContaoSiblingNavigation\Module\SiblingNavigationNews->compile()
>      (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:209)
>   at Contao\Module->generate()
>      (vendor/inspiredminds/contao-sibling-navigation/src/Module/SiblingNavigationNews.php:85)
>   at InspiredMinds\ContaoSiblingNavigation\Module\SiblingNavigationNews->generate()
>      (vendor/contao/core-bundle/src/Resources/contao/elements/ContentModule.php:76)
>   at Contao\ContentModule->generate()
>      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:580)
>   at Contao\Controller::getContentElement(object(ContentModel), 'main')
>      (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:187)
>   at Contao\ModuleArticle->compile()
>      (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:209)
>   at Contao\Module->generate()
>      (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:74)
>   at Contao\ModuleArticle->generate(false)
>      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:520)
>   at Contao\Controller::getArticle(object(ArticleModel), false, false, 'main')
>      (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:371)
>   at Contao\Controller::getFrontendModule('0', 'main')
>      (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:168)
>   at Contao\PageRegular->prepare(object(PageModel))
>      (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:48)
>   at Contao\PageRegular->getResponse(object(PageModel), true)
>      (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:339)
>   at Contao\FrontendIndex->renderPage(object(PageModel))
>      (vendor/symfony/http-kernel/HttpKernel.php:158)
>   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
>      (vendor/symfony/http-kernel/HttpKernel.php:80)
>   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
>      (vendor/symfony/http-kernel/Kernel.php:201)
>   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
>      (web/preview.php:31)

**Comment by fritzmg** [comment]
> Unknown method isPreviewMode

Dieser Fehler ist nun in der neuesten `dev-master` Version behoben. Bitte nochmal testen.

> Hm ... wenn ich [https://github.com/fritzmg/contao-simple-news-urls](url) deinstalliere, klappts auch mit der Fehlermeldung 😉

Ich habe auch diese Extension nochmal getestet, konnte aber keinen Fehler feststellen. Die Extension funktioniert auch noch in Contao 4.9.5. Vermutlich sind hier andere Faktoren im Spiel, die einen unendlichen Redirect auslösen (entweder eine weitere Extension oder eine Server Konfiguration).

**Comment by johannes-bittner** [comment]
Super, funktioniert jetzt einwandfrei. 

Zu contao-simple-news-urls habe ich in einer frischen 4.9.5 herausgefunden, dass es wohl beim Zusammenspiel mit fehlenden Suffixen hakt. Wenn ich /app/config/config.yml anlege mit dem Inhalt: 

`contao:
    url_suffix: ''`

... dann funktioniert auf einer News-Reader-Seite die Preview-Funktion nicht mehr (normaler Aufruf ohne Preview klappt).

**Comment by fritzmg** [comment]
> Super, funktioniert jetzt einwandfrei.

Passt, habe ich als Version `1.2.1` veröffentlicht.

> Zu contao-simple-news-urls habe ich in einer frischen 4.9.5 herausgefunden, dass es wohl beim Zusammenspiel mit fehlenden Suffixen hakt. Wenn ich /app/config/config.yml anlege mit dem Inhalt:
> 
> `contao: url_suffix: ''`
> 
> ... dann funktioniert auf einer News-Reader-Seite die Preview-Funktion nicht mehr (normaler Aufruf ohne Preview klappt).

Hm, bitte dazu im jeweiligen Repository ein Issue anlegen.
