### ISSUE TITLE
Contao 5.0.4: (News-) Sibling-Navigation not rendered in frontend

### ISSUE THREAD

**Issue by CMSworker** [inspiredminds/contao-sibling-navigation#12]
Hello, I did a test with Contao 5.0.4 (local XAMPP installation) with sibling navigation for News only (Events siblings not tested, but it was a full Contao installation with all core bundles, no other extensions installed).

The backend module (at themes) for news-sibling-navi can be created and the module can be added as content element to the page/article with the newsreader.

But the siblings navigation is not rendered in the frontend.

No error, no warning, no stack trace available.

For testing I also created a template copy of "mod_sibling_navigation.html5" and added just `<p>Testoutput</p>` right before the `<a>` links are generated - The template is not at all rendered in the frontend.

**Comment by fritzmg** [comment]
Should be fixed in version `1.3.5`.
