### ISSUE TITLE
Contao 5.3

### ISSUE THREAD

**Issue by jankout** [inspiredminds/contao-sibling-navigation#13]
Hallo, ich möchte mich nur erkundigen, wann man mit einer neuen Version für Contao 5.3 LTS rechnen könnte? Beziehungsweise wie kann man selbst die momentane Version damit kompatibel machen? 

Braucht ihr da jegliche Unterstützung?

**Comment by fritzmg** [comment]
Aktuell verwenden wir diese Extension in keinem Projekt, müsste daher beauftragt werden.

**Comment by fritzmg** [comment]
This extension was already unlocked for Contao 5 since July 2022 and received some Contao 5 fixes in November 2022. @jankout if there is a particular issue that you are experiencing, you will need to mention that.
