### ISSUE TITLE
Forward navigation does not work in multiple day events

### ISSUE THREAD

**Issue by joehi** [inspiredminds/contao-sibling-navigation#2]
On events where the Start date and End date differ, the URL which should link to the next event links instead to the multiple day event itself. So you are trapped with a link to the actual displayed event.

I am using Version 1.1.4.

**Comment by fritzmg** [comment]
Fixed in b44267c3f7c5614540d59cf01d340cde41a18010

**Comment by joehi** [comment]
Vielen Dank für das superschnelle Beheben des Bugs.
