### ISSUE TITLE
Contao 4.4: Sortierung in den Moduleinstellungen wird nicht angezeigt

### ISSUE THREAD

**Issue by saress** [inspiredminds/contao-sibling-navigation#6]
Hallo Fritz,

wir haben gerade bei einer Contao 4.4 Installation festgestellt, dass im Einstellungsbereich des Moduls die Sortieroptionen nicht angezeigt werden, was wohl direkt damit:

https://github.com/inspiredminds/contao-sibling-navigation/blob/8fa6bbbe00b5f026b1eda8d1743e3165f337a814/src/Resources/contao/dca/tl_module.php#L36

zu tun hat. 

Hat es einen speziellen Grund, dass Du hier die Version >=4.5 abfragst? 
Wir haben das testweise mal auf die Version 4.4 geändert und dann funktioniert soweit alles. Soweit ich bei einer aktuellen frischen Installation gesehen habe, ist das Feld auch in der Version 4.4. bereits verfügbar.

Weiters steht in der Beschreibung des Moduls noch folgendes:

If you do not select any news archives or calendars, the sibling navigation will automatically use the news or event entries' archive/calendar.

Wäre schön, wenn das funktionieren würde, allerdings ist das Nachrichtenarchiv ein Pflichtfeld, das man gar nicht leer lassen kann und immer ein entsprechendes Archiv auswählen muss. Bei mehreren getrennten News-Archiven muss man dann unnötig die Pagination-Module kopieren,
nur um die passenden Archive auszuwählen.

Vielen Dank und beste Grüße
Sares

**Comment by fritzmg** [comment]
> Hat es einen speziellen Grund, dass Du hier die Version >=4.5 abfragst?
> Wir haben das testweise mal auf die Version 4.4 geändert und dann funktioniert soweit alles. Soweit ich bei einer aktuellen frischen Installation gesehen habe, ist das Feld auch in der Version 4.4. bereits verfügbar.

Ab Version 4.5 steht in `news_order` etwas anderes drin, als in Contao 4.4. In Contao 4.4 wird das Feld nur für das Newsarchiv verwendet. Ab Contao 4.5 wird es auch für Newslisten verwendet. Ich gehe bei der Verwendung der Sibling Navigation nur vom Newslisten Modul aus - daher gibt es auch keine Einstellung der Sortierung für Contao 4.4.

> Wäre schön, wenn das funktionieren würde, allerdings ist das Nachrichtenarchiv ein Pflichtfeld, das man gar nicht leer lassen kann und immer ein entsprechendes Archiv auswählen muss. Bei mehreren getrennten News-Archiven muss man dann unnötig die Pagination-Module kopieren, nur um die passenden Archive auszuwählen.

Funktionieren tut das prinzipiell ;). Du kannst es testen, in dem du das Feld manuell in der Datenbank leerst. Hier müsste ich noch einen `onload_callback` für das DCA einbauen, damit das Feld für dieses Modul kein Pflichtfeld ist. Aber bis dorthin kannst du dich mit dem erwähnten Workaround behelfen.

Übrigens: bitte in Zukunft separate Tickets für separate Themen erstellen - nicht mehrere Dinge in ein Ticket zusammenfassen.

**Comment by saress** [comment]
Hallo Fritz,

alles klar, vielen Dank für die schnelle Info. Hab gerade nachgeschaut und Du hast natürlich Recht, in der 4.5er wurden weitere Sortieroptionen ergänzt, wie ich gerade im Changelog gesehen hab.

Bezüglich 2 Themen ein Ticket: sorry, mein Fehler, hab nicht aufgepasst und ich gelobe Besserung ;-)

Vielen Dank und beste Grüße
Sares

**Comment by fritzmg** [comment]
Implemented in 707726d78b1c9482eb62dc6e69625ef42da861bc
