### ISSUE TITLE
Modul für Events "spinnt" - Version 4.9.x - dev

### ISSUE THREAD

**Issue by Nightwing0815** [inspiredminds/contao-sibling-navigation#8]
Hallo,

zufällig gestern festgestellt, das für Events das Modul nicht funktioniert (= leeres Modul, nicht im Dropdown wählbar), nach Aktualisierung aller Pakete (da wurde au irgendwas aktualisiert) hats funktioniert. Nach erneuter Aktualisierung nicht mehr.
Aktueller Status: tut nicht.

ToM

**Comment by fritzmg** [comment]
Please try the current `dev-master` branch and see if it is fixed.

**Comment by Nightwing0815** [comment]
Yes, it's fixed. Thanks!
